# Restaurant.create(name:"Casa Mono", cuisine:"Spanish", neighborhood:"Gramercy", date_of_visit:"6/10/2020", user_id: 1)
# Restaurant.create(name:"The Smith", cuisine:"American", neighborhood:"East Village", date_of_visit:"6/30/2020", user_id: 1)
# Restaurant.create(name:"Cocotte", cuisine:"French" , neighborhood:"SoHo", date_of_visit:"7/4/2020", user_id: 1)
# Restaurant.create(name:"Quality Eats", cuisine:"Steakhouse" , neighborhood:"East Village", date_of_visit:"7/10/2020", user_id: 2)
# Restaurant.create(name:"Aunt Jakes", cuisine:"Italian" , neighborhood:"Greenwich Village", date_of_visit:"7/16/2020", user_id: 2)

# Review.create(num_rating:10, comment_rating:"amazing food!", user_id:11, restaurant_id:17)
# Review.create(num_rating:7, comment_rating:"food was standard, service wasn't great", user_id:11, restaurant_id:18)
# Review.create(num_rating:8, comment_rating:"Brunch is incredible here!", user_id:11, restaurant_id:3)
# Review.create(num_rating:9, comment_rating:"Go for the steak, it was incredible!", user_id:12, restaurant_id:4)
# Review.create(num_rating:7, comment_rating:"Decent brunch, pasta is the way to go!", user_id:12, restaurant_id:5)

# User.create(first_name:"Kerri", last_name:"OGorman", username:"kerri lynne", password:"1234")
# User.create(first_name:"Doug", last_name:"Moran", username:"Dougj", password:"kerri")
# # User.create(first_name:"Leslie", last_name:"Kay", username:"LK", password_digest:"pass")
# # User.create(first_name:"Tom", last_name:"Smith", username:"Tommy", password_digest:"word")
